version: '3'

services:
  

    weather-postgres:
      image: postgres:15-alpine
      environment:
        - POSTGRES_DATABASE=weather_dev
        - POSTGRES_USER=weather_dev
        - POSTGRES_PASSWORD=weather_dev

      ports: 
        - 5432:5432
      volumes:
        - postgres-data:/data/db


volumes: 
 postgres-data: 

